### ISSUE TITLE
Server terminates if the port specified in the config file is not available

### ISSUE THREAD

**Issue by kunal-mohta** [fluid-lab/fluid-adaptive-content-service#4]
If the port specified in the server config file is not available, then it terminates with `EADDRINUSE` error message.
Instead, it should use some other available port.
@waharnum What do you think?

**Comment by waharnum** [comment]
@kunal-mohta This is a reasonable behaviour for local development, but dynamically assigning a port range like this can be problematic in production environments, since other systems may be expecting to connect on a particular port. I'd recommend against it as the default behaviour because of this.

**Comment by kunal-mohta** [comment]
Sounds reasonable.
Are such situations generally dealt by termination of the process, in production environments?

**Comment by waharnum** [comment]
@kunal-mohta Yes, the typical behaviour of an application if a port has been configured and is not available is to terminate with an error message.
